import React, { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useSiteContent } from '../context/SiteContentContext'

export default function DynamicPage({ slugOverride }) {
  const params = useParams(); const rawSlug = slugOverride ?? params.slug; const slug=(rawSlug||'').replace(/^\/+/, '')
  const { siteContent, services, projects, team, values, loading: contentLoading } = useSiteContent()
  const [page,setPage]=useState(null); const [sections,setSections]=useState([]); const [loading,setLoading]=useState(true)
  useEffect(()=>{load()},[slug])
  async function load(){
    setLoading(true)
    const {data,error}=await supabase.from('pages').select('*').eq('slug',slug).eq('is_published',true).maybeSingle()
    if(error||!data){setPage(null);setSections([]);setLoading(false);return}
    const {data:rows}=await supabase.from('page_blocks').select('*').eq('page_id',data.id).order('sort_order',{ascending:true})
    let next=(rows||[]).filter(r=>r.block_type==='section').map(r=>r.content||{}).filter(s=>s.blocks)
    setPage(data);setSections(next);setLoading(false)
  }
  if(loading||contentLoading)return <div className="container" style={{padding:'6rem 0'}}>Loading…</div>
  if(!page)return <div className="container" style={{padding:'6rem 0'}}><h1>Page not found</h1><p>The page you’re looking for does not exist.</p></div>
  return <div className="dynamic-page-root" style={{backgroundColor:page.background_color||undefined,backgroundImage:page.background_image?`url(${page.background_image})`:undefined}}>{sections.length?sections.map(s=><section key={s.id} style={{background:s.settings?.background||undefined,padding:s.settings?.padding==='none'?'0':s.settings?.padding==='small'?'36px 0':'80px 0'}}><div className="container" style={{maxWidth:`${s.settings?.maxWidth||1200}px`}}>{s.blocks.map(b=><div style={blockStyle(b.settings)}><RenderBlock key={b.id} block={b} site={siteContent} services={services} projects={projects} team={team} values={values}/></div>)}</div></section>):<div className="container" style={{padding:'6rem 0'}}><div className="page-heading"><p className="eyebrow">{page.name}</p><h1>{page.title}</h1>{page.description&&<p>{page.description}</p>}</div></div>}</div>
}

function blockStyle(c={}){const s={};if(c.textColor)s.color=c.textColor;if(c.fontFamily)s.fontFamily=c.fontFamily;if(c.fontSize)s.fontSize=`${Number(c.fontSize)}px`;if(c.fontWeight)s.fontWeight=c.fontWeight;if(c.lineHeight)s.lineHeight=c.lineHeight;if(c.letterSpacing)s.letterSpacing=`${Number(c.letterSpacing)}px`;if(c.blockBackground)s.background=c.blockBackground;if(c.radius!=null&&c.radius!=='')s.borderRadius=`${Number(c.radius)}px`;if(c.shadow)s.boxShadow=c.shadow;if(c.blockPadding)s.padding=c.blockPadding;if(c.blockMargin)s.margin=c.blockMargin;if(c.maxWidth)s.maxWidth=`${Number(c.maxWidth)}px`;if(c.opacity!=null&&c.opacity!=='')s.opacity=Number(c.opacity);return s}
function resolveLink(c={}){const a=c.action||'url';if(a==='email')return `mailto:${c.email||c.url||''}`;if(a==='phone')return `tel:${c.phone||c.url||''}`;if(a==='whatsapp')return `https://wa.me/${String(c.whatsapp||c.url||'').replace(/\D/g,'')}`;if(['instagram','facebook','tiktok','linkedin'].includes(a))return c[a]||c.url||'#';return c.url||'#'}
function ActionLink({c,className='btn btn-dark',children}){const href=resolveLink(c);const external=/^(https?:|mailto:|tel:)/i.test(href);return external?<a className={className} href={href} target={c.newTab?'_blank':undefined} rel={c.newTab?'noreferrer':undefined}>{children}</a>:<Link className={className} to={href}>{children}</Link>}
function RenderBlock({block,site,services,projects,team,values}){const c=block.settings||{}; if(block.type==='hero')return <div className="hero"><div className="hero-copy"><p className="eyebrow">{c.eyebrow}</p><h1>{c.title}</h1><p className="hero-description">{c.description}</p><div className="btn-group">{c.primaryText&&<ActionLink c={{...c,url:c.primaryUrl,action:c.primaryAction,instagram:c.primaryInstagram,whatsapp:c.primaryWhatsapp,newTab:c.primaryNewTab}}>{c.primaryText}</ActionLink>}{c.secondaryText&&<ActionLink className="text-link" c={{...c,url:c.secondaryUrl,action:c.secondaryAction,newTab:c.secondaryNewTab}}>{c.secondaryText} <span>↗</span></ActionLink>}</div></div><div className="hero-visual">{c.image?<img src={c.image} alt=""/>:<div className="placeholder-visual" aria-label="Image not configured" />}</div></div>; if(block.type==='text')return <div className="page-heading" style={{textAlign:c.alignment||'left'}}><p className="eyebrow">{c.eyebrow}</p>{c.title&&<h1>{c.title}</h1>}<p style={{whiteSpace:'pre-wrap'}}>{c.text}</p></div>; if(block.type==='image')return c.url?<figure style={{margin:0}}><img src={c.url} alt={c.alt||''} style={{width:'100%',height:`${c.height||420}px`,objectFit:c.fit||'cover',display:'block'}}/>{c.caption&&<figcaption>{c.caption}</figcaption>}</figure>:null; if(block.type==='button')return <div style={{textAlign:c.alignment||'left'}}><ActionLink c={c}>{c.text||'Learn more'}</ActionLink></div>; if(block.type==='video')return c.url?<div style={{aspectRatio:'16/9'}}><iframe src={c.url} title={c.title||'Video'} width="100%" height="100%" style={{border:0}} allowFullScreen/></div>:null; if(block.type==='divider')return <hr/>; if(block.type==='spacer')return <div style={{height:Number(c.height)||80}}/>; if(['services','projects','team','values'].includes(block.type))return <Collection type={block.type} title={c.title} eyebrow={c.eyebrow} items={{services,projects,team,values}[block.type]||[]} limit={c.limit}/>; if(block.type==='contact')return <div className="cta-block"><p className="eyebrow">{c.eyebrow}</p><h2>{c.title}</h2><p>{c.description}</p>{site?.email&&<p>{site.email}</p>}{site?.phone&&<p>{site.phone}</p>}<Link className="btn btn-dark" to="/contact">Contact us</Link></div>; return null}
function Collection({type,title,eyebrow,items,limit}){const list=limit?items.slice(0,Number(limit)):items;return <div><div className="section-intro"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><div className={`${type==='services'?'service-grid':type==='projects'?'project-grid':'value-grid'} ${type==='services'?'service-grid-large':''}`}>{list.map((x,i)=><article key={x.id||i} className={type==='projects'?'project-card':type==='values'?'value-card':'service-card'}>{x.image_url&&<div style={{width:'100%',height:'180px',overflow:'hidden',marginBottom:'1rem'}}><img src={x.image_url} alt={x.title||''} style={{width:'100%',height:'100%',objectFit:'cover'}}/></div>}<p className="card-number">{x.category||String(i+1).padStart(2,'0')}</p><h3>{x.title||x.name}</h3><p>{x.description||''}</p></article>)}</div></div>}
